# Generated by Django 4.0.4 on 2022-05-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('trail', models.CharField(max_length=255)),
                ('work_post', models.CharField(max_length=20)),
                ('tabel_num', models.CharField(max_length=20)),
                ('hired', models.DateField()),
                ('order_num', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('period', models.DurationField()),
                ('trips_num', models.DecimalField(decimal_places=0, max_digits=2)),
                ('num_days_worked', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('day_verify', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.worker')),
                ('pers_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.moderator')),
            ],
        ),
    ]
