# Generated by Django 4.0.4 on 2022-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_b',
            field=models.TextField(blank=True, null=True),
        ),
    ]
