# Generated by Django 4.0.4 on 2022-05-29 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data_per_1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='data_per_2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
