# Generated by Django 4.0.4 on 2022-05-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_data_per_1_article_data_per_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обрабатывается'), (1, 'Принят'), (2, 'Ошибка')], default=0),
        ),
    ]
