# Generated by Django 4.0.4 on 2022-05-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moderator',
            table='moderator',
        ),
        migrations.AlterModelTable(
            name='worker',
            table='worker',
        ),
    ]
